[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["data/academy.data.md", "data/courses.data.md", "data/gamefolio.data.md", "data/repofolio.data.md", "data/research.data.md", "data/skills.data.md", "data/work.data.md"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
